"""Single source of truth for Premier Barber & Beauty site content.
Every price/duration below was copied from each pro's live booking page on 2026-09-18.
Update here, then run build.py."""

SITE = {
    'name': 'Premier Barber & Beauty Salon',
    'short': 'Premier Barber & Beauty',
    'domain': 'https://www.premierbarberbeauty.com',
    'phone': '(804) 332-7091',
    'phone_href': 'tel:+18043327091',
    'sms_href': 'sms:+18043327091',
    'street': '11800-G Hull Street Road',
    'city': 'Midlothian',
    'region': 'VA',
    'zip': '23112',
    'geo': (37.4336824, -77.6124863),
    'maps_url': 'https://www.google.com/maps/search/?api=1&query=Premier+Barber+%26+Beauty+Salon+11800+Hull+Street+Road+Midlothian+VA+23112',
    'maps_embed': 'https://www.google.com/maps?q=Premier+Barber+%26+Beauty+Salon,+11800+Hull+Street+Rd,+Midlothian,+VA+23112&z=15&output=embed',
    'instagram': 'https://www.instagram.com/rvapremier/',
    'facebook': 'https://www.facebook.com/PREMIERBARBERANDBEAUTYSALON/',
    'linktree': 'https://linktr.ee/rvapremier',
    # Shop hours as published on Google / Fresha. Individual pros keep their own books.
    'hours': [
        ('Monday', None, None),
        ('Tuesday', '09:00', '19:00'),
        ('Wednesday', '09:00', '19:00'),
        ('Thursday', '09:00', '19:00'),
        ('Friday', '07:00', '19:00'),
        ('Saturday', '07:00', '19:00'),
        ('Sunday', None, None),
    ],
}

# ---------------------------------------------------------------- team
# platform: booksy | styleseat | thecut
TEAM = [
    {
        'slug': 'maal',
        'name': 'Master Barber Maal',
        'first': 'Maal',
        'role': 'Master Barber',
        'kind': 'barber',
        'platform': 'Booksy',
        'book_url': 'https://link.booksy.com/MaalTheBarber',
        'profile_url': 'https://booksy.com/en-us/1077671_master-barber-maal_barber-shop_38109_midlothian',
        'instagram': 'https://www.instagram.com/masterbarbermaal/',
        'ig_handle': '@masterbarbermaal',
        'rating': 5.0,
        'reviews': 89,
        'experience': '15+ years',
        'headline': 'Precision fades, hot-towel shaves, and patience for every age.',
        'bio': [
            'Maal is a master barber with more than 15 years behind the chair and a book that runs from first haircuts to 65-and-up regulars. His signature is a clean blend finished with the razor, done carefully and never rushed.',
            'Clients stay for years. They talk about how carefully he works, how kind he is with kids and seniors, and how he checks every angle before you stand up. He also takes a limited number of mobile and after-hours appointments across the Richmond and Petersburg area.',
        ],
        'specialties': ['Skin fades', 'Tapers', 'Scissor cuts', 'Hot towel shaves', 'Kids & teens', 'Seniors'],
        'hours_note': 'Books most days 8 AM – 7 PM (break 12–1).',
        'portrait': 'maal-portrait',
        'card': 'maal-card',
        'accent_logo': None,
        'menu': [
            ('Adult Haircuts', [
                ('Fade / Taper Haircut', 40, '45 min', 'Any regular fade or taper blend with line up, razor finish and style.'),
                ('Skin Fade Haircut', 45, '50 min', 'Faded down to the skin. Razor finish and style.'),
                ('All Scissor Cut', 45, '45 min', 'Shears only, with trimmers around the edges if you want them.'),
                ('Long Length Scissor Haircut', 50, '45 min', 'All-scissor cut for hair that falls past the middle of the ear.'),
                ('All Even Haircut', 35, '30 min', 'One guard, all even, line up included. Razor finish.'),
                ('Line Up', 25, '30 min', 'Line up with trimmers and razor finish.'),
                ('Senior Haircut (65+)', 30, '30 min', 'Special pricing for ages 65 and older.'),
            ]),
            ('Teens (11–17)', [
                ('Teen Skin Fade', 40, '40 min', 'Any fade down to the skin. Razor finish on request. Styled.'),
                ('Teen All Scissor Haircut', 40, '40 min', ''),
                ('Teen Long Length Scissor Haircut', 45, '40 min', 'For hair past the middle of the ear.'),
                ('Teen Fade / Taper Haircut', 35, '35 min', 'Faded no lower than a zero. Styled.'),
                ('Teen All Even Haircut', 30, '25 min', 'One guard, all even. Styled.'),
                ('Teen Line Up', 20, '20 min', ''),
            ]),
            ('Kids (10 & under)', [
                ('Kids Skin Fade', 35, '35 min', 'Any fade, all the way to the skin. Styled.'),
                ('Kids All Scissor Cut', 35, '35 min', 'Shears only. A good fit for kids who are sensitive to clippers.'),
                ('Kids Fade / Taper Haircut', 30, '30 min', 'Faded no lower than a zero. Styled.'),
                ('Kids All Even Haircut', 25, '25 min', 'One guard, all even.'),
                ('Kids Line Up', 20, '15 min', ''),
            ]),
            ('Shaves & Beard', [
                ('Hot Towel Face Shave', 30, '30 min', 'Full hot-towel shave with lather, razor work and massage.'),
                ('Hot Towel Beard Trim', 25, '25 min', 'Beard trim with a hot towel, shaving gel and razor.'),
                ('Beard Shape Up', 20, '20 min', 'Line up and shape the beard. Razor finish.'),
                ('Beard Line Up', 15, '15 min', 'Beard line up only. Razor finish.'),
            ]),
            ('Extras', [
                ('Eyebrows', 10, '10 min', 'Eyebrows shaped with a straight razor.'),
                ('Shampoo & Conditioner', 10, '5 min', 'Shampoo and condition, styled after if you like.'),
                ('After-Hours Haircut', 100, '1 hr', 'Any full-service cut before or after regular hours. Call Maal to schedule.'),
                ('Mobile Haircut', 150, '1 hr 30 min', 'Maal travels across the Richmond / Petersburg area. Extra fee beyond 45 minutes.'),
            ]),
        ],
        'quotes': [
            ('Antoine', 'Maal has been my barber for almost 3 years now. There is a reason for that. He is definitely a master barber!'),
            ('Danielle', 'Maal is very conscientious and kind. He is a fabulously skilled Master Barber. We are regulars in his chair.'),
            ('Michael', 'Very thorough, patient, makes sure he’s getting perfection! Definitely coming back to him!'),
            ('Aubrey', 'Best barber in the city.'),
            ('Florence', 'He treated my husband with compassion.'),
        ],
    },
    {
        'slug': 'darnell',
        'name': 'OG Barber Darnell',
        'first': 'Darnell',
        'role': 'Barber · 28 Years',
        'kind': 'barber',
        'platform': 'StyleSeat',
        'book_url': 'https://www.styleseat.com/m/v/DarnellDaBarber',
        'profile_url': 'https://www.styleseat.com/m/v/DarnellDaBarber',
        'instagram': 'https://www.instagram.com/darnelldabarber/',
        'ig_handle': '@darnelldabarber',
        'rating': 5.0,
        'reviews': 341,
        'experience': '28 years',
        'headline': 'Brooklyn-trained. 28 years of razor-sharp line-ups.',
        'bio': [
            'Darnell learned the trade in Brooklyn, New York, and has been cutting for 28 years. He worked beside some of the city’s best barbers before bringing that standard to Richmond. He’s also a tattoo artist, which shows in how carefully he handles detail.',
            'His chair is where people come for crisp line-ups, fades, tapers and afros, and for a barber who is patient with kids, including children on the autism spectrum. Clients describe him as professional, personable, on time and meticulous. His goal is simple: to make you look and feel good.',
        ],
        'specialties': ['Fades & tapers', 'Afros', 'Razor line-ups', 'Beard work', 'Kids 2+', 'Line enhancement'],
        'hours_note': 'Sun 10–4 · Wed 2–6 · Thu–Fri 9–6 · Sat 10–5',
        'portrait': 'darnell-portrait',
        'card': 'darnell-card',
        'accent_logo': None,
        'policy': 'Darnell takes a non-refundable deposit at booking. Cancelling within 24 hours costs 50% of the service, and a no-show costs 100%.',
        'menu': [
            ('Adults (13+)', [
                ('Fade, Taper & Afro', 35, '45 min', 'Any style: fade, taper, afro or shear cut, finished with a razor line-up.'),
                ('Fades, Tapers & Afros with Facial Hair', 40, '45 min', 'His most-booked service. Includes the beard.'),
                ('All Even Cut & Baldhead', 30, '45 min', 'All-even cut with a razor line-up.'),
                ('All Even & Baldhead with Facial Hair', 35, '45 min', 'Includes the beard.'),
                ('DarnellDaBarber Gold', 80, '1 hr 30 min', 'Any style with a wash, razor line-up, line enhancer for a fuller hairline, and a hot towel.'),
                ('Senior Adults (60+)', 25, '45 min', 'All cuts.'),
            ]),
            ('Pre-Teens (6–12)', [
                ('Fades, Tapers & Afros', 30, '45 min', ''),
                ('All Even Cut', 25, '45 min', ''),
            ]),
            ('Kids (2–5)', [
                ('Fades, Tapers & Afros', 25, '45 min', ''),
                ('All Even Cut', 20, '45 min', ''),
            ]),
        ],
        'quotes': [
            ('Dan', 'One of the best shape ups I’ve had. Darnell does an amazing job and has a great attention to detail.'),
            ('Chakira', 'One of the best — personable, attentive, thorough. My boys enjoy getting their cuts with Mr. Darnell.'),
            ('Jasmine', 'Darnell has cut my son’s hair twice and has done a wonderful job. He has convenient hours and is easy to work with.'),
            ('Donte’', 'Best barber in the city!!'),
        ],
    },
    {
        'slug': 'ryan',
        'name': 'Ryan In The Cut',
        'first': 'Ryan',
        'role': 'Barber',
        'kind': 'barber',
        'platform': 'theCut',
        'book_url': 'https://book.thecut.co/ryan_inthecut',
        'profile_url': 'https://book.thecut.co/ryan_inthecut',
        'instagram': 'https://www.instagram.com/ryan_inthecut/',
        'ig_handle': '@ryan_inthecut',
        'rating': 5.0,
        'reviews': 87,
        'experience': '3.5+ years',
        'headline': 'Modern mullets, textured crops and tapers that grow out right.',
        'bio': [
            'Ryan is the shop’s go-to for modern styles: textured crops, modern mullets, burst fades and tapers. Every cut is shaped around how your hair actually grows.',
            'Every full cut includes eyebrows and a razor finish. His motto: invest in yourself. His regulars book monthly and say he gets it right every time.',
        ],
        'specialties': ['Modern mullets', 'Textured crops', 'Tapers', 'Burst fades', 'Beard fades'],
        'hours_note': 'Books from 11 AM.',
        'portrait': 'ryan-portrait',
        'card': 'ryan-card',
        'accent_logo': None,
        'menu': [
            ('Cuts', [
                ('Full Cut', 35, '45 min', 'Full haircut including eyebrows, with a razor finish.'),
                ('Full Cut + Beard', 40, '1 hr', 'Full cut including a beard line-up or fade.'),
                ('Kids Cut (12 & under)', 25, '45 min', ''),
            ]),
            ('Line-Ups & Beard', [
                ('Line Up', 25, '30 min', 'Line up only.'),
                ('Line Up / Shave with Beard', 35, '1 hr', 'Line up or hot-towel shave with a beard line-up.'),
                ('Beard Shape Up', 20, '15 min', 'Beard fade or shape up with a razor finish.'),
            ]),
        ],
        'quotes': [
            ('Brian', 'Bro saves my life every month.'),
        ],
    },
    {
        'slug': 'samaya',
        'name': 'Hair by Samaya',
        'first': 'Samaya',
        'role': 'Braider & Wig Specialist',
        'kind': 'beauty',
        'platform': 'Booksy',
        'book_url': 'https://hairbysamaya.booksy.com/a/',
        'profile_url': 'https://booksy.com/en-us/1156708_hairby-samaya_hair-salon_134575_richmond',
        'instagram': 'https://www.instagram.com/hairby.samaya/',
        'ig_handle': '@hairby.samaya',
        'rating': 4.8,
        'reviews': 49,
        'experience': None,
        'headline': 'Knotless, Fulani and stitch braids. Wigs installed and customized.',
        'bio': [
            'Samaya (Sam to her regulars) runs the beauty side of Premier. She does knotless and Fulani braids, freestyle and straight-back stitch braids, custom wig installs, quick weaves, sleek ponytails, silk presses and loc maintenance.',
            'Clients call her “literally the sweetest hairstylist ever” and “very detailed and efficient.” Every wig install includes the braid-down and full customization: bleached knots, plucking, styling and color.',
        ],
        'specialties': ['Knotless braids', 'Fulani / tribal', 'Stitch braids', 'Wig installs', 'Quick weaves', 'Silk press', 'Locs'],
        'hours_note': 'Appointments only. Squeeze-ins aren’t available right now.',
        'portrait': 'samaya-portrait',
        'card': 'samaya-card',
        'accent_logo': 'samaya-logo',
        'policy': 'Bring your own hair. Samaya recommends Ruwa or X-Pression (green pack) braiding hair. Prices marked “+” start there and go up with length and size.',
        'menu': [
            ('Knotless Braids', [
                ('Jumbo Knotless', 120, '2 hr 30 min', ''),
                ('Large Knotless', 150, '4 hr', 'Price starts here.'),
                ('Medium Knotless', 200, '5 hr', 'Price starts here.'),
                ('Smedium Knotless', 275, '7 hr 30 min', 'Price starts here.'),
            ]),
            ('Fulani / Tribal', [
                ('Large Fulani / Tribal Braids', 185, '3 hr 30 min', ''),
                ('Medium Fulani / Tribal Braids', 200, '4 hr 30 min', 'Price starts here.'),
                ('Small Fulani / Tribal Braids', 275, '6 hr 30 min', 'Price starts here.'),
            ]),
            ('Stitch Braids', [
                ('Large Freestyle Stitch Braids', 125, '2 hr 30 min', 'Price starts here.'),
                ('Medium Freestyle Stitch Braids', 160, '5 hr', 'Price starts here.'),
                ('Small Freestyle Stitch Braids', 200, '6 hr 30 min', 'Price starts here.'),
                ('Large Straight-Back Stitch Braids', 100, '3 hr', 'Price starts here.'),
                ('Medium Straight-Back Stitch Braids', 145, '4 hr 30 min', 'Price starts here.'),
                ('Small Straight-Back Stitch Braids', 150, '6 hr', 'Price starts here.'),
                ('Two Feed-In Braids', 75, '45 min', ''),
                ('Men’s Braids / Twists', 75, '3 hr', 'Price starts here.'),
            ]),
            ('Wigs & Weaves', [
                ('Wig Install / Styling', 100, '2 hr 30 min', 'Braid down plus wig customization: bleached knots, plucking, styling and color. Wig not included. Price starts here.'),
                ('Wig / Quick Weave Touch-Up & Restyle', 35, '30 min', 'Doesn’t need to be her install. Come with your hair already glued down.'),
                ('Quick Weave', 120, '3 hr', ''),
                ('Fulani Quick Weave', 145, '3 hr 30 min', 'Braids in the front or side, quick weave for the rest. Hair not provided.'),
                ('Frontal Ponytail', 135, '2 hr 30 min', 'Sleek ponytail with a frontal added. Hair not provided.'),
                ('Crochet', 150, '4 hr', ''),
            ]),
            ('Styling & Locs', [
                ('Silk Press', 50, '1 hr 10 min', 'Wash, blowout and silk press.'),
                ('Sleek Hairstyles', 80, '2 hr 20 min', 'Wash, blow dry, straightening and sleeking. Hair not included. Price starts here.'),
                ('Loc Retwist', 90, '5 hr', 'Price starts here.'),
                ('Starter Locs', 135, '4 hr', ''),
                ('Shape Up', 20, '1 hr', 'Enhancements and face clean-up. Eyebrow slits included.'),
            ]),
        ],
        'quotes': [
            ('Secrit', 'Literally the sweetest hairstylist ever!! Everything’s included and I always feel so comfortable.'),
            ('Jahdai', 'Forever locked in with Sam. She’s so sweet and most of all talented! Nobody else can touch my hair.'),
            ('Cee', 'Very detailed and efficient stylist. I recommend.'),
            ('Antonia', 'Great service, 10 out of 10, very welcoming. My wig looks amazing.'),
            ('Denver', 'She made my hair look perfect and was super sweet!'),
        ],
    },
    {
        'slug': 'adonis',
        'name': 'Adonis Tha Barber',
        'first': 'Adonis',
        'role': 'Barber · Jack of All Fadez',
        'kind': 'barber',
        'platform': 'theCut',
        'book_url': 'https://book.thecut.co/loso',
        'profile_url': 'https://book.thecut.co/loso',
        'instagram': 'https://www.instagram.com/thejackofallfadez/',
        'ig_handle': '@thejackofallfadez',
        'rating': 5.0,
        'reviews': 111,
        'experience': None,
        'headline': 'The Jack of All Fadez. Temp fades, textured fringes and freehand designs.',
        'bio': [
            'Adonis works as “The Jack of All Fadez”: a versatile barber who can do nearly any fade, from temp fades and textured fringes to women’s cuts with designs and freehand art.',
            'He opens early, welcomes walk-ins any time, and asks that you call or text so he knows you’re coming. Parents of children on the spectrum have singled him out for his time and patience.',
        ],
        'specialties': ['Temp fades', 'Textured fringe', 'Designs', 'Women’s cuts', 'Kids', 'Walk-ins'],
        'hours_note': 'Opens at 7:30 AM. Walk-ins welcome.',
        'portrait': 'adonis-portrait',
        'card': 'adonis-card',
        'accent_logo': None,
        'menu': [
            ('Cuts', [
                ('Haircut & Beard', 50, '30 min', 'Any fade or cut you want.'),
                ('Temp Fade', 50, '30 min', 'Sides and back faded, with a line up.'),
                ('Textured Fringe', 80, '1 hr', 'Fade on the temples and back, with a textured top.'),
                ('Haircut with Hair Wash', 60, '40 min', 'Hair washed before the cut.'),
                ('Women’s Haircut', 40, '30 min', 'Any type of fade and style.'),
                ('Women’s Haircut with Design', 50, '45 min', ''),
            ]),
            ('Kids', [
                ('Kids Fade', 40, '30 min', ''),
                ('Kids Cutz', 35, '20 min', 'Any fade.'),
                ('Kids Line Up', 20, '10 min', 'Line up only. Not a taper or temp fade.'),
            ]),
            ('Line-Ups & Add-Ons', [
                ('Adult Line Up', 25, '15 min', 'Line up only. Fades and tapers are booked as haircuts.'),
                ('Hot Towel', 10, '5 min', 'Hot towel at the end of your cut.'),
                ('Enhancement: Black Spray', 10, '5 min', ''),
                ('Enhancement: White Pencil', 10, '5 min', 'Pencil on the outline.'),
            ]),
        ],
        'quotes': [
            ('Kendra', 'If any spectrum parent is looking for a barber, look no further. I appreciate the time and patience you had with my son.'),
        ],
    },
    {
        'slug': 'saint',
        'name': 'Blessed By Saint',
        'first': 'Saint',
        'role': 'Barber',
        'kind': 'barber',
        'platform': 'Booksy',
        'book_url': 'https://blessedbysaint.booksy.com',
        'profile_url': 'https://booksy.com/en-us/166168_blessedbysaint_barber-shop_38109_midlothian',
        'instagram': 'https://www.instagram.com/blessedby_saint/',
        'ig_handle': '@blessedby_saint',
        'rating': 4.9,
        'reviews': 205,
        'experience': None,
        'headline': 'Richmond barber. Big chops, clean cuts, and the same quality every time.',
        'bio': [
            'Saint is a Richmond barber with more than 200 reviews and a steady book of regulars. Every standard cut is tailored to you and includes the beard.',
            'He also handles big chops (cutting off three inches or more), women’s cuts, kids’ cuts and mobile appointments. Walk-ins and appointments are both welcome. His clients’ most common review: “Top tier. Same great quality every time.”',
        ],
        'specialties': ['Tailored cuts', 'Big chops', 'Women’s cuts', 'Kids 4–12', 'Mobile service'],
        'hours_note': 'Walk-ins and appointments welcome.',
        'portrait': 'saint-portrait',
        'card': 'saint-card',
        'accent_logo': 'saint-logo',
        'menu': [
            ('Cuts', [
                ('Haircut (16+)', 52.5, '1 hr', 'Standard haircut tailored to your needs, beard included. Not a big chop.'),
                ('Haircut (Women)', 52.5, '45 min', 'Standard haircut tailored for women.'),
                ('Big Chop', 70, '1 hr', 'For clients cutting off three or more inches of hair.'),
                ('Kids Haircut (4–12)', 30, '30 min', 'Standard haircut tailored for kids.'),
                ('Line Up', 30, '30 min', 'Line up only, beard included.'),
            ]),
        ],
        'quotes': [
            ('Dewon', 'Top tier. Same great quality every time.'),
            ('Allan', 'When I was living in Richmond, Saint was the best barber I ever had. His cuts were always clean.'),
            ('Anthony', 'Best in the city!'),
            ('Lisa', 'Always does an excellent job.'),
        ],
    },
]

# Aggregate social proof, computed from the platforms above
TOTAL_REVIEWS = sum(p['reviews'] for p in TEAM)
AVG_RATING = round(sum(p['rating'] * p['reviews'] for p in TEAM) / TOTAL_REVIEWS, 2)

FAQ = [
    ('Do you take walk-ins?',
     'Yes. Walk-ins are welcome, and several of our barbers (including Adonis and Saint) regularly take them. Appointments are preferred and guarantee your spot, so book online if you’re on a schedule.'),
    ('How do I book?',
     'Every pro at Premier keeps their own book. Tap “Book” on any pro’s card and you’ll go straight to their live calendar on Booksy, StyleSeat or theCut, where you pick a time and confirm in about a minute.'),
    ('Where are you located, and is there parking?',
     'We’re at 11800-G Hull Street Road in Midlothian, VA 23112, serving Richmond, Chesterfield and the surrounding area. There’s easy parking in the lot right outside.'),
    ('Do you cut kids’ hair?',
     'Absolutely. Our barbers cut kids as young as two, with kid, pre-teen and teen pricing. Parents often mention Darnell’s and Adonis’s patience with children on the autism spectrum.'),
    ('Do you do braids, wigs and silk presses?',
     'Yes. Samaya handles the beauty side: knotless, Fulani and stitch braids, wig installs and customization, quick weaves, silk presses, and loc retwists and starter locs.'),
    ('What does a haircut cost?',
     'Standard adult cuts at Premier run from $30 to $52.50 depending on the barber and service. Premium services, like Darnell’s Gold package or Adonis’s textured fringe, are $80. Kids’ cuts start at $20. See the full menu for every price.'),
    ('How do payments and deposits work?',
     'Cards are accepted. Each pro sets their own deposit and cancellation policy on their booking page. For example, Darnell requires a deposit and charges for late cancellations. Check your pro’s page before booking.'),
    ('Is the shop hiring or renting booths?',
     'We periodically open chairs for motivated barbers, stylists, locticians and braiders. Call or text (804) 332-7091 to ask about current availability.'),
]
